### PR TITLE
http version => protocol

### PR DESCRIPTION
**Pull request by LoganWright**

### CODE REVIEW

**Comment by tannernelson** [comment]
I'm all for this but I think @paulofaria was saying something about not being able to use protocols as dictionary keys?

Either way, I think we should try to work around them being protocols as much as possible.

**Comment by LoganWright** [comment]
@tannernelson Good point, I think if we want that, we could implement something like:

```
var key: String {
    return "\(major):\(minor)"
}
```

And use that as the key. It depends how much we're willing to work around the limitation, since yea: `[HTTPVersion : ...]` won't work with this implementation

**Comment by tannernelson** [comment]
I think using a protocol is important enough to merit needing to work around it a little bit internally.

**Comment by paulofaria** [comment]
I don't think protocols are always the best option. I'll open an issue protocols vs concrete types so we can discuss this topic a bit more.

**Comment by bradhilton** [comment]
I'm leaning towards protocol. I suggest typealiasing a `Double` as the dictionary key:
```swift
typealias HTTPVersionKey : Double
```
I think a `Double` would be better than a `String` key because it would be a stricter representation.

**Comment by LoganWright** [comment]
@bradhilton If I understand you correctly, you're saying something like

```
var key: HTTPVersionKey {
  return // get 1.1
}
```

I don't have a problem w/ this, the only tricky part is if we're storing `major` and `minor`, we'd have to combine those into a double somehow which can require some extra logic.

Can you explain the advantage of using a double here, maybe I'm missing something

**Comment by bradhilton** [comment]
I just think that a double would be a better representation than a string for the key, but it's not a big issue to me. For me I just would like to see if we can steer clear of concrete types, like you were suggesting.

**Pull request closed without merging**
