### PR TITLE
Add host parameter to Server.serve()

### PR DESCRIPTION
**Pull request by shnhrrsn**
Binding to a specific host/ip is common behavior in any HTTP server, I think S4 should support this.

### CODE REVIEW

**Comment by paulofaria** [comment]
I think we should add a typealias for `Host` as well.

```
typealias Host = String
```

**Comment by tannernelson** [comment]
I think I read somewhere that you should strive to use native Swift types where possible. I don't know if that applies here.

In my personal experience, it's been extra work for me to see a protocol that accepts say `headers: Headers` and then I have to look that up and see it's just a typealias to `[HeaderKey: String]` or something. This is not as much of a problem when using Xcode, but it's super annoying in Sublime Text.

What is the advantage the typealias offers?

**Comment by paulofaria** [comment]
The problem is that without the `typealias` the API is:

`func serve(responder: Responder, on: String, at: Int) throws`

what's on? what's at?

**Comment by tannernelson** [comment]
`func serve(responder: Responder, host: String, port: Int) throws`

I think this is the clearest option personally.

**Comment by paulofaria** [comment]
Yeah, but I'm not sure that follows Swift guidelines.

Maybe we just don't use the typealias? The documentation can explain the parameters. That seems to be the approach apple uses.

```
public mutating func insert(newElement: Element, at i: Int)
array.insert(5, at: 2)
```

```
func serve(responder: Responder, on host: String, at port: Int) throws
try server.serve(app, on: "localhost", at: 8080)
```

**Comment by Danappelxx** [comment]
I like this option:
```swift
func serve(responder: Responder, on host: String, at port: Int) throws
try server.serve(app, on: "localhost", at: 8080)
```
It's clear what's going on when reading the code, and only requires looking at the method declaration when writing it.

**Comment by tannernelson** [comment]
screen shot 2016-04-01 at 2 58 54 pm

@Danappelxx my main concern was that the internal name wouldn't show up on Xcode's hints, but it looks like they do. So that does seem like a perfect solution.

**Comment by tannernelson** [comment]
screen shot 2016-04-01 at 3 04 03 pm

Works cross module :)

**Comment by shnhrrsn** [comment]
I'm good with this as well, shall I drop the typealiases?

**Comment by paulofaria** [comment]
yeah @tannernelson that was my concern as well, that's why I proposed the `typealias` but it's not necessary. we should remove `Host` and `Port`. @shnhrrsn Can you update please?

Also I think maybe we could provide some extensions with default values:

```swift
extension Server {
    func serve(responder: Responder, at port: Int) throws {
        self.serve(responder: Responder, on: "localhost", at: port)
}
```

**Comment by shnhrrsn** [comment]
@paulofaria I added default host as 0.0.0.0 not localhost, since binding on localhost would only be available locally

**Comment by paulofaria** [comment]
LGTM? :rocket: ?

**Pull request merged**
